// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateStatus) DeepCopyInto(out *CertificateStatus) {
	*out = *in
	in.Acquired.DeepCopyInto(&out.Acquired)
	in.NotBefore.DeepCopyInto(&out.NotBefore)
	in.NotAfter.DeepCopyInto(&out.NotAfter)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateStatus.
func (in *CertificateStatus) DeepCopy() *CertificateStatus {
	if in == nil {
		return nil
	}
	out := new(CertificateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionProcessStatus) DeepCopyInto(out *ConnectionProcessStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionProcessStatus.
func (in *ConnectionProcessStatus) DeepCopy() *ConnectionProcessStatus {
	if in == nil {
		return nil
	}
	out := new(ConnectionProcessStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionStatus) DeepCopyInto(out *ConnectionStatus) {
	*out = *in
	in.Established.DeepCopyInto(&out.Established)
	in.Renewed.DeepCopyInto(&out.Renewed)
	in.LastSync.DeepCopyInto(&out.LastSync)
	in.LastSuccess.DeepCopyInto(&out.LastSuccess)
	in.CertificateStatus.DeepCopyInto(&out.CertificateStatus)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionStatus.
func (in *ConnectionStatus) DeepCopy() *ConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(ConnectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementInfo) DeepCopyInto(out *ManagementInfo) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementInfo.
func (in *ManagementInfo) DeepCopy() *ManagementInfo {
	if in == nil {
		return nil
	}
	out := new(ManagementInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SynchronizationStatus) DeepCopyInto(out *SynchronizationStatus) {
	*out = *in
	in.LastAttempt.DeepCopyInto(&out.LastAttempt)
	in.LastSuccessfulFetch.DeepCopyInto(&out.LastSuccessfulFetch)
	in.LastSuccessfulApplication.DeepCopyInto(&out.LastSuccessfulApplication)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SynchronizationStatus.
func (in *SynchronizationStatus) DeepCopy() *SynchronizationStatus {
	if in == nil {
		return nil
	}
	out := new(SynchronizationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemBrokerConnection) DeepCopyInto(out *SystemBrokerConnection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemBrokerConnection.
func (in *SystemBrokerConnection) DeepCopy() *SystemBrokerConnection {
	if in == nil {
		return nil
	}
	out := new(SystemBrokerConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SystemBrokerConnection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemBrokerConnectionList) DeepCopyInto(out *SystemBrokerConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SystemBrokerConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemBrokerConnectionList.
func (in *SystemBrokerConnectionList) DeepCopy() *SystemBrokerConnectionList {
	if in == nil {
		return nil
	}
	out := new(SystemBrokerConnectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SystemBrokerConnectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemBrokerConnectionSpec) DeepCopyInto(out *SystemBrokerConnectionSpec) {
	*out = *in
	out.ManagementInfo = in.ManagementInfo
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemBrokerConnectionSpec.
func (in *SystemBrokerConnectionSpec) DeepCopy() *SystemBrokerConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(SystemBrokerConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemBrokerConnectionStatus) DeepCopyInto(out *SystemBrokerConnectionStatus) {
	*out = *in
	if in.ConnectionStatus != nil {
		in, out := &in.ConnectionStatus, &out.ConnectionStatus
		*out = new(ConnectionStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.SynchronizationStatus != nil {
		in, out := &in.SynchronizationStatus, &out.SynchronizationStatus
		*out = new(SynchronizationStatus)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemBrokerConnectionStatus.
func (in *SystemBrokerConnectionStatus) DeepCopy() *SystemBrokerConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(SystemBrokerConnectionStatus)
	in.DeepCopyInto(out)
	return out
}
