// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kyma-project/kyma/components/system-broker-agent/pkg/apis/applicationconnector/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterSystems implements ClusterSystemInterface
type FakeClusterSystems struct {
	Fake *FakeApplicationconnectorV1alpha1
}

var clustersystemsResource = schema.GroupVersionResource{Group: "applicationconnector", Version: "v1alpha1", Resource: "clustersystems"}

var clustersystemsKind = schema.GroupVersionKind{Group: "applicationconnector", Version: "v1alpha1", Kind: "ClusterSystem"}

// Get takes name of the clusterSystem, and returns the corresponding clusterSystem object, and an error if there is any.
func (c *FakeClusterSystems) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterSystem, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(clustersystemsResource, name), &v1alpha1.ClusterSystem{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterSystem), err
}

// List takes label and field selectors, and returns the list of ClusterSystems that match those selectors.
func (c *FakeClusterSystems) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterSystemList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(clustersystemsResource, clustersystemsKind, opts), &v1alpha1.ClusterSystemList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterSystemList{ListMeta: obj.(*v1alpha1.ClusterSystemList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClusterSystemList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterSystems.
func (c *FakeClusterSystems) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(clustersystemsResource, opts))
}

// Create takes the representation of a clusterSystem and creates it.  Returns the server's representation of the clusterSystem, and an error, if there is any.
func (c *FakeClusterSystems) Create(ctx context.Context, clusterSystem *v1alpha1.ClusterSystem, opts v1.CreateOptions) (result *v1alpha1.ClusterSystem, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(clustersystemsResource, clusterSystem), &v1alpha1.ClusterSystem{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterSystem), err
}

// Update takes the representation of a clusterSystem and updates it. Returns the server's representation of the clusterSystem, and an error, if there is any.
func (c *FakeClusterSystems) Update(ctx context.Context, clusterSystem *v1alpha1.ClusterSystem, opts v1.UpdateOptions) (result *v1alpha1.ClusterSystem, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(clustersystemsResource, clusterSystem), &v1alpha1.ClusterSystem{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterSystem), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterSystems) UpdateStatus(ctx context.Context, clusterSystem *v1alpha1.ClusterSystem, opts v1.UpdateOptions) (*v1alpha1.ClusterSystem, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(clustersystemsResource, "status", clusterSystem), &v1alpha1.ClusterSystem{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterSystem), err
}

// Delete takes name of the clusterSystem and deletes it. Returns an error if one occurs.
func (c *FakeClusterSystems) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(clustersystemsResource, name), &v1alpha1.ClusterSystem{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterSystems) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(clustersystemsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterSystemList{})
	return err
}

// Patch applies the patch and returns the patched clusterSystem.
func (c *FakeClusterSystems) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterSystem, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(clustersystemsResource, name, pt, data, subresources...), &v1alpha1.ClusterSystem{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterSystem), err
}
