// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/kyma-project/kyma/components/system-broker-agent/pkg/clientcs/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// ClusterSystems returns a ClusterSystemInformer.
	ClusterSystems() ClusterSystemInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// ClusterSystems returns a ClusterSystemInformer.
func (v *version) ClusterSystems() ClusterSystemInformer {
	return &clusterSystemInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
