// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kyma-project/kyma/components/system-broker-agent/pkg/apis/compass/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSystemBrokerConnections implements SystemBrokerConnectionInterface
type FakeSystemBrokerConnections struct {
	Fake *FakeCompassV1alpha1
}

var systembrokerconnectionsResource = schema.GroupVersionResource{Group: "compass.kyma-project.io", Version: "v1alpha1", Resource: "systembrokerconnections"}

var systembrokerconnectionsKind = schema.GroupVersionKind{Group: "compass.kyma-project.io", Version: "v1alpha1", Kind: "SystemBrokerConnection"}

// Get takes name of the systemBrokerConnection, and returns the corresponding systemBrokerConnection object, and an error if there is any.
func (c *FakeSystemBrokerConnections) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SystemBrokerConnection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(systembrokerconnectionsResource, name), &v1alpha1.SystemBrokerConnection{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SystemBrokerConnection), err
}

// List takes label and field selectors, and returns the list of SystemBrokerConnections that match those selectors.
func (c *FakeSystemBrokerConnections) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SystemBrokerConnectionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(systembrokerconnectionsResource, systembrokerconnectionsKind, opts), &v1alpha1.SystemBrokerConnectionList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SystemBrokerConnectionList{ListMeta: obj.(*v1alpha1.SystemBrokerConnectionList).ListMeta}
	for _, item := range obj.(*v1alpha1.SystemBrokerConnectionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested systemBrokerConnections.
func (c *FakeSystemBrokerConnections) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(systembrokerconnectionsResource, opts))
}

// Create takes the representation of a systemBrokerConnection and creates it.  Returns the server's representation of the systemBrokerConnection, and an error, if there is any.
func (c *FakeSystemBrokerConnections) Create(ctx context.Context, systemBrokerConnection *v1alpha1.SystemBrokerConnection, opts v1.CreateOptions) (result *v1alpha1.SystemBrokerConnection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(systembrokerconnectionsResource, systemBrokerConnection), &v1alpha1.SystemBrokerConnection{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SystemBrokerConnection), err
}

// Update takes the representation of a systemBrokerConnection and updates it. Returns the server's representation of the systemBrokerConnection, and an error, if there is any.
func (c *FakeSystemBrokerConnections) Update(ctx context.Context, systemBrokerConnection *v1alpha1.SystemBrokerConnection, opts v1.UpdateOptions) (result *v1alpha1.SystemBrokerConnection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(systembrokerconnectionsResource, systemBrokerConnection), &v1alpha1.SystemBrokerConnection{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SystemBrokerConnection), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSystemBrokerConnections) UpdateStatus(ctx context.Context, systemBrokerConnection *v1alpha1.SystemBrokerConnection, opts v1.UpdateOptions) (*v1alpha1.SystemBrokerConnection, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(systembrokerconnectionsResource, "status", systemBrokerConnection), &v1alpha1.SystemBrokerConnection{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SystemBrokerConnection), err
}

// Delete takes name of the systemBrokerConnection and deletes it. Returns an error if one occurs.
func (c *FakeSystemBrokerConnections) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(systembrokerconnectionsResource, name), &v1alpha1.SystemBrokerConnection{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSystemBrokerConnections) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(systembrokerconnectionsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.SystemBrokerConnectionList{})
	return err
}

// Patch applies the patch and returns the patched systemBrokerConnection.
func (c *FakeSystemBrokerConnections) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SystemBrokerConnection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(systembrokerconnectionsResource, name, pt, data, subresources...), &v1alpha1.SystemBrokerConnection{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SystemBrokerConnection), err
}
