// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kyma-project/kyma/components/system-broker-agent/pkg/apis/compass/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// SystemBrokerConnectionLister helps list SystemBrokerConnections.
type SystemBrokerConnectionLister interface {
	// List lists all SystemBrokerConnections in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.SystemBrokerConnection, err error)
	// Get retrieves the SystemBrokerConnection from the index for a given name.
	Get(name string) (*v1alpha1.SystemBrokerConnection, error)
	SystemBrokerConnectionListerExpansion
}

// systemBrokerConnectionLister implements the SystemBrokerConnectionLister interface.
type systemBrokerConnectionLister struct {
	indexer cache.Indexer
}

// NewSystemBrokerConnectionLister returns a new SystemBrokerConnectionLister.
func NewSystemBrokerConnectionLister(indexer cache.Indexer) SystemBrokerConnectionLister {
	return &systemBrokerConnectionLister{indexer: indexer}
}

// List lists all SystemBrokerConnections in the indexer.
func (s *systemBrokerConnectionLister) List(selector labels.Selector) (ret []*v1alpha1.SystemBrokerConnection, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.SystemBrokerConnection))
	})
	return ret, err
}

// Get retrieves the SystemBrokerConnection from the index for a given name.
func (s *systemBrokerConnectionLister) Get(name string) (*v1alpha1.SystemBrokerConnection, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("systembrokerconnection"), name)
	}
	return obj.(*v1alpha1.SystemBrokerConnection), nil
}
