// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// SystemBrokerConnectionListerExpansion allows custom methods to be added to
// SystemBrokerConnectionLister.
type SystemBrokerConnectionListerExpansion interface{}
