// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	applicationconnectorv1alpha1 "github.com/kyma-project/kyma/components/system-broker-agent/pkg/apis/applicationconnector/v1alpha1"
	versioned "github.com/kyma-project/kyma/components/system-broker-agent/pkg/client/applicationconnector/clientset/versioned"
	internalinterfaces "github.com/kyma-project/kyma/components/system-broker-agent/pkg/client/applicationconnector/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/kyma-project/kyma/components/system-broker-agent/pkg/client/applicationconnector/listers/applicationconnector/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SystemMappingInformer provides access to a shared informer and lister for
// SystemMappings.
type SystemMappingInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.SystemMappingLister
}

type systemMappingInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSystemMappingInformer constructs a new informer for SystemMapping type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSystemMappingInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSystemMappingInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSystemMappingInformer constructs a new informer for SystemMapping type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSystemMappingInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApplicationconnectorV1alpha1().SystemMappings(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApplicationconnectorV1alpha1().SystemMappings(namespace).Watch(context.TODO(), options)
			},
		},
		&applicationconnectorv1alpha1.SystemMapping{},
		resyncPeriod,
		indexers,
	)
}

func (f *systemMappingInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSystemMappingInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *systemMappingInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&applicationconnectorv1alpha1.SystemMapping{}, f.defaultInformer)
}

func (f *systemMappingInformer) Lister() v1alpha1.SystemMappingLister {
	return v1alpha1.NewSystemMappingLister(f.Informer().GetIndexer())
}
