// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ClusterSystemListerExpansion allows custom methods to be added to
// ClusterSystemLister.
type ClusterSystemListerExpansion interface{}
