// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/kyma-project/kyma/components/system-broker-agent/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// SystemBrokerConnections returns a SystemBrokerConnectionInformer.
	SystemBrokerConnections() SystemBrokerConnectionInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// SystemBrokerConnections returns a SystemBrokerConnectionInformer.
func (v *version) SystemBrokerConnections() SystemBrokerConnectionInformer {
	return &systemBrokerConnectionInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
