// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	compassv1alpha1 "github.com/kyma-project/kyma/components/system-broker-agent/pkg/apis/compass/v1alpha1"
	versioned "github.com/kyma-project/kyma/components/system-broker-agent/pkg/client/clientset/versioned"
	internalinterfaces "github.com/kyma-project/kyma/components/system-broker-agent/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/kyma-project/kyma/components/system-broker-agent/pkg/client/listers/compass/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SystemBrokerConnectionInformer provides access to a shared informer and lister for
// SystemBrokerConnections.
type SystemBrokerConnectionInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.SystemBrokerConnectionLister
}

type systemBrokerConnectionInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewSystemBrokerConnectionInformer constructs a new informer for SystemBrokerConnection type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSystemBrokerConnectionInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSystemBrokerConnectionInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredSystemBrokerConnectionInformer constructs a new informer for SystemBrokerConnection type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSystemBrokerConnectionInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CompassV1alpha1().SystemBrokerConnections().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CompassV1alpha1().SystemBrokerConnections().Watch(context.TODO(), options)
			},
		},
		&compassv1alpha1.SystemBrokerConnection{},
		resyncPeriod,
		indexers,
	)
}

func (f *systemBrokerConnectionInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSystemBrokerConnectionInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *systemBrokerConnectionInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&compassv1alpha1.SystemBrokerConnection{}, f.defaultInformer)
}

func (f *systemBrokerConnectionInformer) Lister() v1alpha1.SystemBrokerConnectionLister {
	return v1alpha1.NewSystemBrokerConnectionLister(f.Informer().GetIndexer())
}
