apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: clustersystems.applicationconnector.kyma-project.io
spec:
  group: applicationconnector.kyma-project.io
  version: v1alpha1
  scope: Cluster
  names:
    plural: clustersystems
    singular: clustersystem
    kind: ClusterSystem
    shortNames:
    - cs
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            compassMetadata:
              type: object
              required:
              - "authentication"
              properties:
                authentication:
                  type: object
                  required:
                  - "clientIds"
                  properties:
                    clientIds:
                      type: array
                      items:
                        type: string
            services:
              type: array
              items:
                type: object
                required:
                - "id"
                - "name"
                - "displayName"
                - "description"
                - "entries"
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  identifier:
                    type: string
                  displayName:
                    type: string
                  description:
                    type: string
                  longDescription:
                    type: string
                  entries:
                    type: array
                    items:
                      type: object
                      required:
                      - "type"
                      properties:
                        type:
                          type: string
                          enum:
                          - "API"
                          - "Events"
                        targetUrl:
                          type: string
                        credentials:
                          type: object
                          required:
                          - "type"
                          - "secretName"
                          properties:
                            type:
                              type: string
                            secretName:
                              type: string
                            authenticationUrl:
                              type: string
                            csrfInfo:
                              type: object
                              required:
                              - "tokenEndpointURL"
                              properties:
                                tokenEndpointURL:
                                  type: string
            tags:
              type: array
              items:
                type: string
