// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/kyma-project/kyma/components/system-broker-agent/pkg/apis/compass/v1alpha1"
	scheme "github.com/kyma-project/kyma/components/system-broker-agent/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SystemBrokerConnectionsGetter has a method to return a SystemBrokerConnectionInterface.
// A group's client should implement this interface.
type SystemBrokerConnectionsGetter interface {
	SystemBrokerConnections() SystemBrokerConnectionInterface
}

// SystemBrokerConnectionInterface has methods to work with SystemBrokerConnection resources.
type SystemBrokerConnectionInterface interface {
	Create(ctx context.Context, systemBrokerConnection *v1alpha1.SystemBrokerConnection, opts v1.CreateOptions) (*v1alpha1.SystemBrokerConnection, error)
	Update(ctx context.Context, systemBrokerConnection *v1alpha1.SystemBrokerConnection, opts v1.UpdateOptions) (*v1alpha1.SystemBrokerConnection, error)
	UpdateStatus(ctx context.Context, systemBrokerConnection *v1alpha1.SystemBrokerConnection, opts v1.UpdateOptions) (*v1alpha1.SystemBrokerConnection, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.SystemBrokerConnection, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.SystemBrokerConnectionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SystemBrokerConnection, err error)
	SystemBrokerConnectionExpansion
}

// systemBrokerConnections implements SystemBrokerConnectionInterface
type systemBrokerConnections struct {
	client rest.Interface
}

// newSystemBrokerConnections returns a SystemBrokerConnections
func newSystemBrokerConnections(c *CompassV1alpha1Client) *systemBrokerConnections {
	return &systemBrokerConnections{
		client: c.RESTClient(),
	}
}

// Get takes name of the systemBrokerConnection, and returns the corresponding systemBrokerConnection object, and an error if there is any.
func (c *systemBrokerConnections) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SystemBrokerConnection, err error) {
	result = &v1alpha1.SystemBrokerConnection{}
	err = c.client.Get().
		Resource("systembrokerconnections").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SystemBrokerConnections that match those selectors.
func (c *systemBrokerConnections) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SystemBrokerConnectionList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.SystemBrokerConnectionList{}
	err = c.client.Get().
		Resource("systembrokerconnections").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested systemBrokerConnections.
func (c *systemBrokerConnections) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("systembrokerconnections").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a systemBrokerConnection and creates it.  Returns the server's representation of the systemBrokerConnection, and an error, if there is any.
func (c *systemBrokerConnections) Create(ctx context.Context, systemBrokerConnection *v1alpha1.SystemBrokerConnection, opts v1.CreateOptions) (result *v1alpha1.SystemBrokerConnection, err error) {
	result = &v1alpha1.SystemBrokerConnection{}
	err = c.client.Post().
		Resource("systembrokerconnections").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(systemBrokerConnection).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a systemBrokerConnection and updates it. Returns the server's representation of the systemBrokerConnection, and an error, if there is any.
func (c *systemBrokerConnections) Update(ctx context.Context, systemBrokerConnection *v1alpha1.SystemBrokerConnection, opts v1.UpdateOptions) (result *v1alpha1.SystemBrokerConnection, err error) {
	result = &v1alpha1.SystemBrokerConnection{}
	err = c.client.Put().
		Resource("systembrokerconnections").
		Name(systemBrokerConnection.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(systemBrokerConnection).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *systemBrokerConnections) UpdateStatus(ctx context.Context, systemBrokerConnection *v1alpha1.SystemBrokerConnection, opts v1.UpdateOptions) (result *v1alpha1.SystemBrokerConnection, err error) {
	result = &v1alpha1.SystemBrokerConnection{}
	err = c.client.Put().
		Resource("systembrokerconnections").
		Name(systemBrokerConnection.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(systemBrokerConnection).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the systemBrokerConnection and deletes it. Returns an error if one occurs.
func (c *systemBrokerConnections) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("systembrokerconnections").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *systemBrokerConnections) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("systembrokerconnections").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched systemBrokerConnection.
func (c *systemBrokerConnections) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SystemBrokerConnection, err error) {
	result = &v1alpha1.SystemBrokerConnection{}
	err = c.client.Patch(pt).
		Resource("systembrokerconnections").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
