// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/kyma-project/kyma/components/system-broker-agent/pkg/apis/applicationconnector/v1alpha1"
	scheme "github.com/kyma-project/kyma/components/system-broker-agent/pkg/clientcs/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ClusterSystemsGetter has a method to return a ClusterSystemInterface.
// A group's client should implement this interface.
type ClusterSystemsGetter interface {
	ClusterSystems() ClusterSystemInterface
}

// ClusterSystemInterface has methods to work with ClusterSystem resources.
type ClusterSystemInterface interface {
	Create(ctx context.Context, clusterSystem *v1alpha1.ClusterSystem, opts v1.CreateOptions) (*v1alpha1.ClusterSystem, error)
	Update(ctx context.Context, clusterSystem *v1alpha1.ClusterSystem, opts v1.UpdateOptions) (*v1alpha1.ClusterSystem, error)
	UpdateStatus(ctx context.Context, clusterSystem *v1alpha1.ClusterSystem, opts v1.UpdateOptions) (*v1alpha1.ClusterSystem, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ClusterSystem, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ClusterSystemList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterSystem, err error)
	ClusterSystemExpansion
}

// clusterSystems implements ClusterSystemInterface
type clusterSystems struct {
	client rest.Interface
}

// newClusterSystems returns a ClusterSystems
func newClusterSystems(c *ApplicationconnectorV1alpha1Client) *clusterSystems {
	return &clusterSystems{
		client: c.RESTClient(),
	}
}

// Get takes name of the clusterSystem, and returns the corresponding clusterSystem object, and an error if there is any.
func (c *clusterSystems) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterSystem, err error) {
	result = &v1alpha1.ClusterSystem{}
	err = c.client.Get().
		Resource("clustersystems").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterSystems that match those selectors.
func (c *clusterSystems) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterSystemList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ClusterSystemList{}
	err = c.client.Get().
		Resource("clustersystems").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterSystems.
func (c *clusterSystems) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("clustersystems").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a clusterSystem and creates it.  Returns the server's representation of the clusterSystem, and an error, if there is any.
func (c *clusterSystems) Create(ctx context.Context, clusterSystem *v1alpha1.ClusterSystem, opts v1.CreateOptions) (result *v1alpha1.ClusterSystem, err error) {
	result = &v1alpha1.ClusterSystem{}
	err = c.client.Post().
		Resource("clustersystems").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterSystem).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a clusterSystem and updates it. Returns the server's representation of the clusterSystem, and an error, if there is any.
func (c *clusterSystems) Update(ctx context.Context, clusterSystem *v1alpha1.ClusterSystem, opts v1.UpdateOptions) (result *v1alpha1.ClusterSystem, err error) {
	result = &v1alpha1.ClusterSystem{}
	err = c.client.Put().
		Resource("clustersystems").
		Name(clusterSystem.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterSystem).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *clusterSystems) UpdateStatus(ctx context.Context, clusterSystem *v1alpha1.ClusterSystem, opts v1.UpdateOptions) (result *v1alpha1.ClusterSystem, err error) {
	result = &v1alpha1.ClusterSystem{}
	err = c.client.Put().
		Resource("clustersystems").
		Name(clusterSystem.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterSystem).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the clusterSystem and deletes it. Returns an error if one occurs.
func (c *clusterSystems) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("clustersystems").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterSystems) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("clustersystems").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched clusterSystem.
func (c *clusterSystems) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterSystem, err error) {
	result = &v1alpha1.ClusterSystem{}
	err = c.client.Patch(pt).
		Resource("clustersystems").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
