{{- range $key, $value := .Values.certs -}}
{{- $_ := set $ "key" $key }}
{{- $_ := set $ "value" $value }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $value.name | lower |replace " " "-"}}-helm-certs-removal-acc
  namespace: {{ $value.namespace }}
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $value.name | lower | replace " " "-"}}-helm-certs-removal-role
  namespace: {{ $value.namespace }}
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
rules:
  - apiGroups: ["*"]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "delete", "watch", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $value.name | lower | replace " " "-"}}-helm-certs-removal-rb
  namespace: {{ $value.namespace }}
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $value.name | lower | replace " " "-"}}-helm-certs-removal-role
subjects:
- kind: ServiceAccount
  name: {{ $value.name | lower | replace " " "-"}}-helm-certs-removal-acc
  namespace: {{ $value.namespace }}
{{- end }}
