apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}-helm-certs-removal-backup
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/resource-policy: keep
    helm.sh/hook-weight: "1"
  labels:
    release: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ template "name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  template:
    metadata:
      name: {{ .Chart.Name }}-helm-certs-removal-backup
      namespace: {{ .Values.global.namespace }}
      annotations:
        sidecar.istio.io/inject: “false”
      labels:
        release: {{ .Release.Name }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        app.kubernetes.io/name: {{ template "name" . }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Chart.Name }}-helm-certs-removal-backup
      restartPolicy: Never
      containers:
        - name: helm-certs-removal-backup
          image: "{{ .Values.jobs.image.repository }}:{{ .Values.jobs.image.tag }}"
          command:
            - /bin/bash
            - -c
            - |-
{{ tpl (.Files.Get "files/certs-backup.sh" | printf "%s" | indent 14) . }}
          securityContext:
            runAsUser: {{ .Values.global.podSecurityPolicy.runAsUser }}
            privileged: {{ .Values.global.podSecurityPolicy.privileged }}
            allowPrivilegeEscalation: {{ .Values.global.podSecurityPolicy.allowPrivilegeEscalation }}
        {{- if .Values.global.priorityClassName }}
      priorityClassName: {{ .Values.global.priorityClassName }}
        {{- end }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name | lower |replace " " "-"}}-helm-certs-removal-backup
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Chart.Name | lower | replace " " "-"}}-helm-certs-removal-backup
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
rules:
  - apiGroups: ["*"]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "delete", "watch", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Chart.Name | lower | replace " " "-"}}-helm-certs-removal-backup
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Chart.Name | lower | replace " " "-"}}-helm-certs-removal-backup
subjects:
  - kind: ServiceAccount
    name: {{ .Chart.Name | lower | replace " " "-"}}-helm-certs-removal-backup
    namespace: {{ .Release.Namespace }}
